"""PostgreSQL database layer."""

import json
import re
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from typing import Optional

import psycopg
from psycopg.errors import UndefinedTable
from psycopg import sql
from psycopg.rows import dict_row

from .config import (
    PG_DATABASE,
    PG_DSN,
    PG_HOST,
    PG_PASSWORD,
    PG_PORT,
    PG_SCHEMA,
    PG_SETTINGS_TABLE,
    PG_SSLMODE,
    PG_TASKS_TABLE,
    PROJECTS_ROOT,
    PG_USER,
)
from .models import Stats, TaskCreate, TaskInDB, TaskStatus

PROJECT_PASTEL_COLORS = (
    "#f8c8dc",
    "#ffd9b3",
    "#ffe9a8",
    "#d4f0c0",
    "#bdebdc",
    "#c7e9ff",
    "#d9d0ff",
    "#fbd3e9",
    "#cfe8ff",
    "#fde2c5",
)
HEX_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


def _validate_ident(name: str, what: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name or ""):
        raise ValueError(f"Invalid {what}: {name!r}")
    return name


SCHEMA_NAME = _validate_ident(PG_SCHEMA, "schema")
TASKS_TABLE = _validate_ident(PG_TASKS_TABLE, "tasks table")
SETTINGS_TABLE = _validate_ident(PG_SETTINGS_TABLE, "settings table")


def _tasks_ref():
    return sql.SQL("{}.{}").format(sql.Identifier(SCHEMA_NAME), sql.Identifier(TASKS_TABLE))


def _settings_ref():
    return sql.SQL("{}.{}").format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SETTINGS_TABLE))


def _tasks_with_agent_select():
    return sql.SQL(
        """
        SELECT
            t.*,
            aa.name AS agent_account_name,
            aa.shortname AS agent_account_shortname,
            COALESCE(a.name, aa.name, aa.shortname) AS agent_name,
            a.color AS agent_color
        FROM {} t
        LEFT JOIN {}.agents_accounts aa ON aa.id = t.agent_account_id
        LEFT JOIN {}.agents a ON a.id = aa.agent_id
        """
    ).format(_tasks_ref(), sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME))


def _db_kwargs() -> dict:
    if PG_DSN:
        return {"conninfo": PG_DSN, "row_factory": dict_row}
    return {
        "host": PG_HOST,
        "port": PG_PORT,
        "dbname": PG_DATABASE,
        "user": PG_USER,
        "password": PG_PASSWORD,
        "sslmode": PG_SSLMODE,
        "row_factory": dict_row,
    }


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _parse_dt(val) -> Optional[datetime]:
    if val is None:
        return None
    if isinstance(val, datetime):
        if val.tzinfo is None:
            return val.replace(tzinfo=timezone.utc)
        return val
    if isinstance(val, str):
        return datetime.fromisoformat(val)
    return None


def _normalize_project_color(color: Optional[str]) -> Optional[str]:
    if color is None:
        return None
    value = str(color).strip()
    if not value:
        return None
    if not HEX_COLOR_RE.fullmatch(value):
        raise ValueError("Invalid color format, expected #RRGGBB")
    return value.lower()


def _pick_next_project_color(cur) -> str:
    cur.execute(
        sql.SQL("SELECT COUNT(*) AS cnt FROM {}.projects WHERE deleted_at IS NULL").format(sql.Identifier(SCHEMA_NAME))
    )
    row = cur.fetchone() or {"cnt": 0}
    idx = int(row["cnt"] or 0) % len(PROJECT_PASTEL_COLORS)
    return PROJECT_PASTEL_COLORS[idx]


def _row_to_task(row: dict) -> TaskInDB:
    d = dict(row)
    for field in ("scheduled_at", "next_run_at", "created_at", "started_at", "completed_at", "notified_at"):
        if field in d:
            d[field] = _parse_dt(d[field])
    # PostgreSQL bool -> bool; Pydantic handles this for bool field.
    return TaskInDB(**d)


@contextmanager
def _connect():
    conn = psycopg.connect(**_db_kwargs())
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(SCHEMA_NAME)))

        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    prompt TEXT NOT NULL,
                    subject TEXT,
                    working_dir TEXT,
                    provider TEXT,
                    status TEXT NOT NULL DEFAULT 'pending',
                    priority INTEGER NOT NULL DEFAULT 5,
                    scheduled_at TIMESTAMPTZ,
                    next_run_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL,
                    started_at TIMESTAMPTZ,
                    completed_at TIMESTAMPTZ,
                    result TEXT,
                    src JSONB,
                    error TEXT,
                    retry_count INTEGER NOT NULL DEFAULT 0,
                    max_retries INTEGER NOT NULL DEFAULT 5,
                    exit_code INTEGER,
                    model_used TEXT,
                    skip_permissions BOOLEAN DEFAULT FALSE,
                    model TEXT,
                    session_id TEXT,
                    parent_task_id BIGINT,
                    tg_chat_id BIGINT,
                    notified_at TIMESTAMPTZ,
                    recurrence TEXT
                )
                """
            ).format(_tasks_ref())
        )

        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {} (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            ).format(_settings_ref())
        )

        # Agent accounts table in shared hubstaff schema.
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {}.agents_accounts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    shortname VARCHAR(255) NOT NULL UNIQUE,
                    agent_id BIGINT NOT NULL,
                    login TEXT,
                    pass TEXT,
                    token TEXT,
                    login_mode VARCHAR(64),
                    created_at TIMESTAMP WITHOUT TIME ZONE,
                    updated_at TIMESTAMP WITHOUT TIME ZONE
                )
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        cur.execute(
            sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.agents_accounts (agent_id)").format(
                sql.Identifier("idx_agents_accounts_agent_id"),
                sql.Identifier(SCHEMA_NAME),
            )
        )
        cur.execute(
            sql.SQL(
                "ALTER TABLE {}.agents_accounts ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1"
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        cur.execute(
            sql.SQL(
                "ALTER TABLE {}.agents_accounts ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT FALSE"
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        # If no active account is marked for an agent yet, make the newest one active.
        cur.execute(
            sql.SQL(
                """
                WITH ranked AS (
                    SELECT id, agent_id,
                           ROW_NUMBER() OVER (PARTITION BY agent_id ORDER BY id DESC) AS rn
                    FROM {}.agents_accounts
                ),
                missing AS (
                    SELECT agent_id
                    FROM {}.agents_accounts
                    GROUP BY agent_id
                    HAVING BOOL_OR(is_active) = FALSE
                )
                UPDATE {}.agents_accounts aa
                SET is_active = TRUE
                FROM ranked r
                JOIN missing m ON m.agent_id = r.agent_id
                WHERE aa.id = r.id AND r.rn = 1
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME))
        )
        for col_sql in [
            "ADD COLUMN IF NOT EXISTS percent_5h DOUBLE PRECISION",
            "ADD COLUMN IF NOT EXISTS percent_7d DOUBLE PRECISION",
            "ADD COLUMN IF NOT EXISTS balance_tokens BIGINT",
            "ADD COLUMN IF NOT EXISTS reset_5h TIMESTAMPTZ",
            "ADD COLUMN IF NOT EXISTS reset_7d TIMESTAMPTZ",
            "ADD COLUMN IF NOT EXISTS claude_credentials JSONB",
        ]:
            cur.execute(
                sql.SQL("ALTER TABLE {}.agents_accounts {}").format(
                    sql.Identifier(SCHEMA_NAME),
                    sql.SQL(col_sql),
                )
            )
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {}.prompts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    shortname VARCHAR(255) NOT NULL,
                    message TEXT NOT NULL,
                    options JSONB,
                    status SMALLINT NOT NULL DEFAULT 1,
                    created_at TIMESTAMP WITHOUT TIME ZONE,
                    updated_at TIMESTAMP WITHOUT TIME ZONE
                )
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        cur.execute(
            sql.SQL(
                "ALTER TABLE {}.prompts ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1"
            ).format(sql.Identifier(SCHEMA_NAME))
        )

        # Workers table
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {}.workers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    shortname VARCHAR(255) NOT NULL UNIQUE,
                    role VARCHAR(255),
                    is_agent BOOLEAN NOT NULL DEFAULT FALSE,
                    agent_id BIGINT,
                    status SMALLINT NOT NULL DEFAULT 0,
                    avatar_url VARCHAR(512),
                    created_at TIMESTAMP WITHOUT TIME ZONE,
                    updated_at TIMESTAMP WITHOUT TIME ZONE
                )
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )

        # worker_id / task_status_id columns in tasks
        cur.execute(sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS worker_id BIGINT").format(_tasks_ref()))
        cur.execute(sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS task_status_id BIGINT").format(_tasks_ref()))

        # Task statuses reference table
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {}.tasks_statuses (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nom SMALLINT,
                    name VARCHAR(255) NOT NULL,
                    shortname VARCHAR(255) NOT NULL UNIQUE,
                    status_to VARCHAR(64),
                    color VARCHAR(32),
                    status SMALLINT NOT NULL DEFAULT 1,
                    created_at TIMESTAMP WITHOUT TIME ZONE,
                    updated_at TIMESTAMP WITHOUT TIME ZONE
                )
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        # nom column migration (for existing tables created before this field)
        cur.execute(
            sql.SQL(
                "ALTER TABLE {}.tasks_statuses ADD COLUMN IF NOT EXISTS nom SMALLINT"
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        # Seed default task statuses
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.tasks_statuses (id, nom, name, shortname, status_to, color, status, created_at, updated_at)
                VALUES
                  (1, 5, 'Успешно завершена',        'done',             'completed', '#22c55e', 1, NOW(), NOW()),
                  (2, 6, 'Завершена с ошибкой',       'failed',           'failed',    '#ef4444', 1, NOW(), NOW()),
                  (3, 2, 'В работе',                  'in_progress',      'running',   '#3b82f6', 1, NOW(), NOW()),
                  (4, 1, 'Новая',                     'new',              'pending',   '#6b7280', 1, NOW(), NOW()),
                  (5, 3, 'Ожидает подтверждения',     'pending_approval', NULL,        '#f59e0b', 1, NOW(), NOW()),
                  (6, 4, 'Ожидает тестирования',      'pending_test',     NULL,        '#8b5cf6', 1, NOW(), NOW())
                ON CONFLICT (id) DO NOTHING
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        # Back-fill nom for seed rows where nom is still NULL
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.tasks_statuses SET nom = v.nom
                FROM (VALUES (1,5),(2,6),(3,2),(4,1),(5,3),(6,4)) AS v(id, nom)
                WHERE {}.tasks_statuses.id = v.id AND {}.tasks_statuses.nom IS NULL
                """
            ).format(
                sql.Identifier(SCHEMA_NAME),
                sql.Identifier(SCHEMA_NAME),
                sql.Identifier(SCHEMA_NAME),
            )
        )

        # Priorities reference table
        cur.execute(
            sql.SQL(
                """
                CREATE TABLE IF NOT EXISTS {}.priorities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    shortname VARCHAR(255) NOT NULL UNIQUE,
                    icon VARCHAR(512),
                    status SMALLINT NOT NULL DEFAULT 1,
                    created_at TIMESTAMP WITHOUT TIME ZONE,
                    updated_at TIMESTAMP WITHOUT TIME ZONE
                )
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )
        # Seed default Jira priorities (NEW icons style)
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.priorities (id, name, shortname, icon, status, created_at, updated_at)
                VALUES
                  (1,  'Blocker',  'blocker',  'https://jira.atlassian.com/images/icons/priorities/blocker.svg',  1, NOW(), NOW()),
                  (2,  'Critical', 'critical', 'https://jira.atlassian.com/images/icons/priorities/critical.svg', 1, NOW(), NOW()),
                  (3,  'Major',    'major',    'https://jira.atlassian.com/images/icons/priorities/major.svg',    1, NOW(), NOW()),
                  (4,  'Highest',  'highest',  'https://jira.atlassian.com/images/icons/priorities/highest.svg',  1, NOW(), NOW()),
                  (5,  'High',     'high',     'https://jira.atlassian.com/images/icons/priorities/high.svg',     1, NOW(), NOW()),
                  (6,  'Medium',   'medium',   'https://jira.atlassian.com/images/icons/priorities/medium.svg',   1, NOW(), NOW()),
                  (7,  'Low',      'low',      'https://jira.atlassian.com/images/icons/priorities/low.svg',      1, NOW(), NOW()),
                  (8,  'Lowest',   'lowest',   'https://jira.atlassian.com/images/icons/priorities/lowest.svg',   1, NOW(), NOW()),
                  (9,  'Minor',    'minor',    'https://jira.atlassian.com/images/icons/priorities/minor.svg',    1, NOW(), NOW()),
                  (10, 'Trivial',  'trivial',  'https://jira.atlassian.com/images/icons/priorities/trivial.svg',  1, NOW(), NOW())
                ON CONFLICT (id) DO NOTHING
                """
            ).format(sql.Identifier(SCHEMA_NAME))
        )

        # avatar_url column in workers
        cur.execute(
            sql.SQL("ALTER TABLE {}.workers ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512)").format(
                sql.Identifier(SCHEMA_NAME)
            )
        )

        try:
            cur.execute(
                sql.SQL(
                    "ALTER TABLE {}.projects ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ"
                ).format(sql.Identifier(SCHEMA_NAME))
            )
            cur.execute(
                sql.SQL(
                    "ALTER TABLE {}.projects ADD COLUMN IF NOT EXISTS color VARCHAR(7)"
                ).format(sql.Identifier(SCHEMA_NAME))
            )
            cur.execute(
                sql.SQL(
                    """
                    SELECT id
                    FROM {}.projects
                    WHERE COALESCE(TRIM(color), '') = ''
                    ORDER BY id
                    """
                ).format(sql.Identifier(SCHEMA_NAME))
            )
            rows = cur.fetchall()
            for idx, row in enumerate(rows):
                cur.execute(
                    sql.SQL("UPDATE {}.projects SET color = %s WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
                    (PROJECT_PASTEL_COLORS[idx % len(PROJECT_PASTEL_COLORS)], row["id"]),
                )
        except UndefinedTable:
            pass

        try:
            cur.execute(
                sql.SQL(
                    "ALTER TABLE {}.agents ADD COLUMN IF NOT EXISTS color VARCHAR(7)"
                ).format(sql.Identifier(SCHEMA_NAME))
            )
            cur.execute(
                sql.SQL(
                    """
                    UPDATE {}.agents
                    SET color = CASE
                        WHEN LOWER(shortname) = 'codex' THEN '#38bdf8'
                        WHEN LOWER(shortname) = 'claude' THEN '#8b5cf6'
                        WHEN LOWER(shortname) = 'openclaude' THEN '#a16207'
                        ELSE color
                    END
                    WHERE COALESCE(TRIM(color), '') = ''
                      AND LOWER(shortname) IN ('codex', 'claude', 'openclaude')
                    """
                ).format(sql.Identifier(SCHEMA_NAME))
            )
        except UndefinedTable:
            pass

        # Non-destructive migrations for existing tables.
        for col_sql in [
            "ADD COLUMN IF NOT EXISTS provider TEXT",
            "ADD COLUMN IF NOT EXISTS model_used TEXT",
            "ADD COLUMN IF NOT EXISTS skip_permissions BOOLEAN DEFAULT FALSE",
            "ADD COLUMN IF NOT EXISTS session_id TEXT",
            "ADD COLUMN IF NOT EXISTS parent_task_id BIGINT",
            "ADD COLUMN IF NOT EXISTS model TEXT",
            "ADD COLUMN IF NOT EXISTS tg_chat_id BIGINT",
            "ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ",
            "ADD COLUMN IF NOT EXISTS recurrence TEXT",
            "ADD COLUMN IF NOT EXISTS agent_account_id BIGINT",
            "ADD COLUMN IF NOT EXISTS src JSONB",
            "ADD COLUMN IF NOT EXISTS agent_prompt TEXT",
            "ADD COLUMN IF NOT EXISTS subject TEXT",
            "ADD COLUMN IF NOT EXISTS worker_id BIGINT",
        ]:
            cur.execute(sql.SQL("ALTER TABLE {} {}").format(_tasks_ref(), sql.SQL(col_sql)))

        idx_status = sql.Identifier(f"idx_{TASKS_TABLE}_status")
        idx_runnable = sql.Identifier(f"idx_{TASKS_TABLE}_runnable")
        cur.execute(
            sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} (status)").format(idx_status, _tasks_ref())
        )
        cur.execute(
            sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} (status, priority, next_run_at)").format(
                idx_runnable, _tasks_ref()
            )
        )


def create_task(task: TaskCreate) -> TaskInDB:
    subject = task.subject or (task.prompt.splitlines()[0][:255] if task.prompt else None)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {} (
                    prompt, subject, agent_prompt, working_dir, provider, status, priority,
                    scheduled_at, created_at, max_retries, skip_permissions,
                    model, session_id, parent_task_id, tg_chat_id, recurrence, worker_id, task_status_id
                )
                VALUES (%s, %s, %s, %s, %s, 'pending', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """
            ).format(_tasks_ref()),
            (
                task.prompt,
                subject,
                task.agent_prompt or None,
                task.working_dir,
                task.provider,
                task.priority,
                task.scheduled_at,
                _now(),
                task.max_retries,
                bool(task.skip_permissions),
                task.model,
                task.session_id,
                task.parent_task_id,
                task.tg_chat_id,
                task.recurrence,
                task.worker_id,
                task.task_status_id,
            ),
        )
        task_id = cur.fetchone()["id"]
        result = get_task(task_id, conn=conn)
    touch_project_last_used_by_task(task_id)
    return result


def get_task(task_id: int, *, conn=None) -> Optional[TaskInDB]:
    def _query(c):
        with c.cursor() as cur:
            cur.execute(
                sql.SQL("{} WHERE t.id = %s").format(_tasks_with_agent_select()),
                (task_id,),
            )
            row = cur.fetchone()
            return _row_to_task(row) if row else None

    if conn:
        return _query(conn)
    with _connect() as c:
        return _query(c)


def list_tasks(status: Optional[TaskStatus] = None, limit: int = 50, offset: int = 0):
    with _connect() as conn, conn.cursor() as cur:
        if status:
            cur.execute(
                sql.SQL("{} WHERE t.status = %s ORDER BY t.created_at DESC LIMIT %s OFFSET %s").format(
                    _tasks_with_agent_select()
                ),
                (status.value, limit, offset),
            )
        else:
            cur.execute(
                sql.SQL("{} ORDER BY t.created_at DESC LIMIT %s OFFSET %s").format(_tasks_with_agent_select()),
                (limit, offset),
            )
        return [_row_to_task(r) for r in cur.fetchall()]


def get_next_runnable() -> Optional[TaskInDB]:
    now = _now()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                WITH next_task AS (
                    SELECT id
                    FROM {}
                    WHERE status IN ('pending', 'rate_limited')
                      AND (scheduled_at IS NULL OR scheduled_at <= %s)
                      AND (next_run_at IS NULL OR next_run_at <= %s)
                    ORDER BY priority ASC, created_at ASC
                    FOR UPDATE SKIP LOCKED
                    LIMIT 1
                )
                UPDATE {} t
                SET status = 'running', started_at = %s
                FROM next_task
                WHERE t.id = next_task.id
                RETURNING t.*
                """
            ).format(_tasks_ref(), _tasks_ref()),
            (now, now, _now()),
        )
        row = cur.fetchone()
        return _row_to_task(row) if row else None


def mark_completed(
    task_id: int,
    result: str,
    exit_code: int = 0,
    model_used: str = None,
    session_id: str = None,
    src: Optional[dict] = None,
):
    src_payload = json.dumps(src, ensure_ascii=False) if src is not None else None
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}
                SET status = 'completed',
                    result = %s,
                    src = COALESCE(%s::jsonb, src),
                    exit_code = %s,
                    completed_at = %s,
                    model_used = %s,
                    session_id = COALESCE(%s, session_id)
                WHERE id = %s
                """
            ).format(_tasks_ref()),
            (result, src_payload, exit_code, _now(), model_used, session_id, task_id),
        )
    touch_project_last_used_by_task(task_id)


def mark_failed(task_id: int, error: str, exit_code: int = 1, src: Optional[dict] = None):
    src_payload = json.dumps(src, ensure_ascii=False) if src is not None else None
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                "UPDATE {} SET status = 'failed', error = %s, src = COALESCE(%s::jsonb, src), exit_code = %s, completed_at = %s WHERE id = %s"
            ).format(
                _tasks_ref()
            ),
            (error, src_payload, exit_code, _now(), task_id),
        )
    touch_project_last_used_by_task(task_id)


def mark_rate_limited(task_id: int, next_run_at: datetime, error: str = None):
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}
                SET status = 'rate_limited',
                    next_run_at = %s,
                    retry_count = retry_count + 1,
                    error = COALESCE(%s, error)
                WHERE id = %s
                """
            ).format(_tasks_ref()),
            (next_run_at, error, task_id),
        )


def cancel_task(task_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                "UPDATE {} SET status = 'cancelled', completed_at = %s WHERE id = %s AND status IN ('pending', 'rate_limited')"
            ).format(_tasks_ref()),
            (_now(), task_id),
        )
        return cur.rowcount > 0


def touch_project_last_used_by_task(task_id: int) -> bool:
    """Set projects.last_used_at for project matching task working_dir."""
    now = _now()
    base_root = (PROJECTS_ROOT or "/www/wwwroot").rstrip("/")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                WITH t AS (
                    SELECT NULLIF(REGEXP_REPLACE(TRIM(working_dir), '/+$', ''), '') AS wd
                    FROM {}
                    WHERE id = %s
                    LIMIT 1
                )
                UPDATE {}.projects p
                SET last_used_at = %s
                FROM t
                WHERE p.deleted_at IS NULL
                  AND t.wd IS NOT NULL
                  AND (
                    REGEXP_REPLACE(TRIM(p.folder), '/+$', '') = t.wd
                    OR REGEXP_REPLACE(
                        TRIM(
                          CASE
                            WHEN p.folder LIKE '/%%' THEN p.folder
                            ELSE %s || '/' || p.folder
                          END
                        ),
                        '/+$',
                        ''
                      ) = t.wd
                  )
                """
            ).format(_tasks_ref(), sql.Identifier(SCHEMA_NAME)),
            (task_id, now, base_root),
        )
        return cur.rowcount > 0


def update_priority(task_id: int, priority: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {} SET priority = %s WHERE id = %s AND status IN ('pending', 'rate_limited')").format(
                _tasks_ref()
            ),
            (priority, task_id),
        )
        return cur.rowcount > 0


def delete_task(task_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("DELETE FROM {} WHERE id = %s").format(_tasks_ref()), (task_id,))
        return cur.rowcount > 0


def get_stats() -> Stats:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("SELECT status, COUNT(*) AS cnt FROM {} GROUP BY status").format(_tasks_ref()))
        rows = cur.fetchall()
        data = {row["status"]: row["cnt"] for row in rows}
        total = sum(data.values())
        return Stats(
            pending=data.get("pending", 0),
            running=data.get("running", 0),
            completed=data.get("completed", 0),
            failed=data.get("failed", 0),
            rate_limited=data.get("rate_limited", 0),
            cancelled=data.get("cancelled", 0),
            total=total,
        )


def get_setting(key: str, default: str = None) -> Optional[str]:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(sql.SQL("SELECT value FROM {} WHERE key = %s").format(_settings_ref()), (key,))
        row = cur.fetchone()
        return row["value"] if row else default


def set_setting(key: str, value: str):
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {} (key, value)
                VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """
            ).format(_settings_ref()),
            (key, value),
        )


def is_paused() -> bool:
    return get_setting("worker_paused", "0") == "1"


def parse_recurrence(recurrence: str) -> Optional[datetime]:
    """Parse recurrence string and return next run datetime (UTC)."""
    if not recurrence:
        return None
    s = recurrence.strip().lower()
    m = re.fullmatch(r"(\d+)([mh])", s)
    if m:
        n, unit = int(m.group(1)), m.group(2)
        delta = timedelta(minutes=n) if unit == "m" else timedelta(hours=n)
        return datetime.now(timezone.utc) + delta
    m = re.fullmatch(r"daily@(\d{1,2}):(\d{2})", s)
    if m:
        hour, minute = int(m.group(1)), int(m.group(2))
        now = datetime.now(timezone.utc)
        candidate = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
        if candidate <= now:
            candidate += timedelta(days=1)
        return candidate
    return None


def get_cost_stats() -> dict:
    """Parse Cost lines from completed task results and aggregate."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                "SELECT result, provider, completed_at FROM {} WHERE status='completed' AND result LIKE %s AND completed_at IS NOT NULL"
            ).format(_tasks_ref()),
            ("%Cost: $%",),
        )
        rows = cur.fetchall()

    now = datetime.now(timezone.utc)
    today_str = now.date().isoformat()
    week_ago = now - timedelta(days=7)

    total = today = week = 0.0
    by_provider: dict = {}

    for row in rows:
        m = re.search(r"Cost: \$(\d+\.\d+)", row["result"] or "")
        if not m:
            continue
        cost = float(m.group(1))
        completed = _parse_dt(row["completed_at"])
        provider = row["provider"] or "claude"

        total += cost
        by_provider[provider] = round(by_provider.get(provider, 0.0) + cost, 6)
        if completed and completed.date().isoformat() == today_str:
            today += cost
        if completed and completed >= week_ago:
            week += cost

    return {"today": round(today, 6), "week": round(week, 6), "total": round(total, 6), "by_provider": by_provider}


def get_pending_notifications() -> list:
    """Return completed/failed tasks with a tg_chat_id that haven't been notified yet."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                {}
                WHERE t.tg_chat_id IS NOT NULL
                  AND t.notified_at IS NULL
                  AND t.status IN ('completed', 'failed')
                """
            ).format(_tasks_with_agent_select())
        )
        rows = cur.fetchall()
        return [_row_to_task(r) for r in rows]


def mark_notified(task_id: int):
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {} SET notified_at = %s WHERE id = %s").format(_tasks_ref()),
            (_now(), task_id),
        )


def recover_running():
    """Reset any 'running' tasks back to 'pending' (crash recovery)."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {} SET status = 'pending', started_at = NULL WHERE status = 'running'").format(
                _tasks_ref()
            )
        )


def reset_task(task_id: int) -> bool:
    """Reset a single stuck 'running' task back to 'pending'."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {} SET status = 'pending', started_at = NULL WHERE id = %s AND status = 'running'").format(
                _tasks_ref()
            ),
            (task_id,),
        )
        return cur.rowcount > 0


def purge_old(before_days: int = 7) -> int:
    with _connect() as conn, conn.cursor() as cur:
        cutoff = datetime.now(timezone.utc) - timedelta(days=before_days)
        cur.execute(
            sql.SQL(
                "DELETE FROM {} WHERE status IN ('completed', 'failed', 'cancelled') AND completed_at < %s"
            ).format(_tasks_ref()),
            (cutoff,),
        )
        return cur.rowcount


def list_projects(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    """Return projects from {schema}.projects with fields id/name/folder."""
    try:
        with _connect() as conn, conn.cursor() as cur:
            if search:
                like = f"%{search.strip()}%"
                cur.execute(
                    sql.SQL(
                        """
                        SELECT id, name, shortname, folder, color, comment
                        FROM {}.projects
                        WHERE deleted_at IS NULL
                          AND folder IS NOT NULL
                          AND folder <> ''
                          AND (name ILIKE %s OR folder ILIKE %s)
                        ORDER BY last_used_at DESC NULLS LAST, name ASC
                        LIMIT %s
                        """
                    ).format(sql.Identifier(SCHEMA_NAME)),
                    (like, like, limit),
                )
            else:
                cur.execute(
                    sql.SQL(
                        """
                        SELECT id, name, shortname, folder, color, comment
                        FROM {}.projects
                        WHERE deleted_at IS NULL
                          AND folder IS NOT NULL
                          AND folder <> ''
                        ORDER BY last_used_at DESC NULLS LAST, name ASC
                        LIMIT %s
                        """
                    ).format(sql.Identifier(SCHEMA_NAME)),
                    (limit,),
                )
            return [dict(r) for r in cur.fetchall()]
    except UndefinedTable:
        return []


def list_projects_admin(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, folder, color, comment, last_used_at, created_at, updated_at
                    FROM {}.projects
                    WHERE deleted_at IS NULL
                      AND (name ILIKE %s OR shortname ILIKE %s OR folder ILIKE %s)
                    ORDER BY last_used_at DESC NULLS LAST, id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (like, like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, folder, color, comment, last_used_at, created_at, updated_at
                    FROM {}.projects
                    WHERE deleted_at IS NULL
                    ORDER BY last_used_at DESC NULLS LAST, id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_project(
    name: str,
    shortname: str,
    folder: str,
    comment: Optional[str] = None,
    color: Optional[str] = None,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    normalized_color = _normalize_project_color(color)
    with _connect() as conn, conn.cursor() as cur:
        if normalized_color is None:
            normalized_color = _pick_next_project_color(cur)
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.projects
                    (name, shortname, folder, color, comment, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING id, name, shortname, folder, color, comment, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, folder, normalized_color, comment, now, now),
        )
        return dict(cur.fetchone())


def update_project(
    project_id: int,
    name: str,
    shortname: str,
    folder: str,
    comment: Optional[str] = None,
    color: Optional[str] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    normalized_color = _normalize_project_color(color)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.projects
                SET name = %s,
                    shortname = %s,
                    folder = %s,
                    color = %s,
                    comment = %s,
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, folder, normalized_color, comment, now, project_id),
        )
        return cur.rowcount > 0


def delete_project(project_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.projects WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (project_id,),
        )
        return cur.rowcount > 0


def list_agents(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, email, priority, status, color, created_at, updated_at
                    FROM {}.agents
                    WHERE deleted_at IS NULL
                      AND (name ILIKE %s OR shortname ILIKE %s OR COALESCE(email, '') ILIKE %s)
                    ORDER BY id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (like, like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, email, priority, status, color, created_at, updated_at
                    FROM {}.agents
                    WHERE deleted_at IS NULL
                    ORDER BY id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def list_active_agents(limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT id, name, shortname, email, priority, status, color, created_at, updated_at
                FROM {}.agents
                WHERE deleted_at IS NULL
                  AND status = 1
                ORDER BY priority ASC, id ASC
                LIMIT %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (limit,),
        )
        return [dict(r) for r in cur.fetchall()]


def create_agent(
    name: str,
    shortname: str,
    email: Optional[str] = None,
    priority: int = 0,
    status: int = 1,
    color: Optional[str] = None,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    normalized_color = _normalize_project_color(color)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.agents
                    (name, shortname, email, priority, status, color, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, name, shortname, email, priority, status, color, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, email, priority, status, normalized_color, now, now),
        )
        return dict(cur.fetchone())


def update_agent(
    agent_id: int,
    name: str,
    shortname: str,
    email: Optional[str],
    priority: int,
    status: int,
    color: Optional[str] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    normalized_color = _normalize_project_color(color)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.agents
                SET name = %s,
                    shortname = %s,
                    email = %s,
                    priority = %s,
                    status = %s,
                    color = %s,
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, email, priority, status, normalized_color, now, agent_id),
        )
        return cur.rowcount > 0


def delete_agent(agent_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.agents WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (agent_id,),
        )
        return cur.rowcount > 0


def list_agents_accounts(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT aa.id, aa.name, aa.shortname, aa.agent_id, a.name AS agent_name,
                           aa.status, aa.is_active,
                           aa.percent_5h, aa.percent_7d, aa.balance_tokens, aa.reset_5h, aa.reset_7d,
                           aa.login, aa.pass, aa.token, aa.login_mode, aa.claude_credentials, aa.created_at, aa.updated_at
                    FROM {}.agents_accounts aa
                    LEFT JOIN {}.agents a ON a.id = aa.agent_id
                    WHERE aa.name ILIKE %s OR aa.shortname ILIKE %s OR COALESCE(aa.login, '') ILIKE %s
                    ORDER BY aa.id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
                (like, like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT aa.id, aa.name, aa.shortname, aa.agent_id, a.name AS agent_name,
                           aa.status, aa.is_active,
                           aa.percent_5h, aa.percent_7d, aa.balance_tokens, aa.reset_5h, aa.reset_7d,
                           aa.login, aa.pass, aa.token, aa.login_mode, aa.claude_credentials, aa.created_at, aa.updated_at
                    FROM {}.agents_accounts aa
                    LEFT JOIN {}.agents a ON a.id = aa.agent_id
                    ORDER BY aa.id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_agent_account(
    name: str,
    shortname: str,
    agent_id: int,
    login: Optional[str],
    password: Optional[str],
    token: Optional[str],
    login_mode: Optional[str],
    status: int = 1,
    is_active: bool = False,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        if is_active:
            cur.execute(
                sql.SQL("UPDATE {}.agents_accounts SET is_active = FALSE WHERE agent_id = %s").format(
                    sql.Identifier(SCHEMA_NAME)
                ),
                (agent_id,),
            )
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.agents_accounts
                    (name, shortname, agent_id, login, pass, token, login_mode, status, is_active, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, name, shortname, agent_id, status, is_active, login, pass, token, login_mode, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, agent_id, login, password, token, login_mode, status, is_active, now, now),
        )
        return dict(cur.fetchone())


def update_agent_account(
    account_id: int,
    name: str,
    shortname: str,
    agent_id: int,
    login: Optional[str],
    password: Optional[str],
    token: Optional[str],
    login_mode: Optional[str],
    status: Optional[int] = None,
    is_active: Optional[bool] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        if is_active:
            cur.execute(
                sql.SQL(
                    "UPDATE {}.agents_accounts SET is_active = FALSE WHERE agent_id = %s AND id <> %s"
                ).format(sql.Identifier(SCHEMA_NAME)),
                (agent_id, account_id),
            )
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.agents_accounts
                SET name = %s,
                    shortname = %s,
                    agent_id = %s,
                    login = %s,
                    pass = %s,
                    token = %s,
                    login_mode = %s,
                    status = COALESCE(%s, status),
                    is_active = COALESCE(%s, is_active),
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, agent_id, login, password, token, login_mode, status, is_active, now, account_id),
        )
        return cur.rowcount > 0


def delete_agent_account(account_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.agents_accounts WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (account_id,),
        )
        return cur.rowcount > 0


def get_agent_account(account_id: int) -> Optional[dict]:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id, a.name AS agent_name, a.shortname AS agent_shortname,
                       aa.status, aa.is_active,
                       aa.percent_5h, aa.percent_7d, aa.balance_tokens, aa.reset_5h, aa.reset_7d,
                       aa.login, aa.pass, aa.token, aa.login_mode, aa.claude_credentials, aa.created_at, aa.updated_at
                FROM {}.agents_accounts aa
                LEFT JOIN {}.agents a ON a.id = aa.agent_id
                WHERE aa.id = %s
                LIMIT 1
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
            (account_id,),
        )
        row = cur.fetchone()
        return dict(row) if row else None


def list_agent_accounts_for_relogin(agent_id: int, exclude_account_id: Optional[int] = None, limit: int = 50) -> list[dict]:
    """List candidate accounts of the same agent that have stored credentials."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id,
                       aa.status, aa.is_active,
                       aa.percent_5h, aa.percent_7d, aa.balance_tokens, aa.reset_5h, aa.reset_7d,
                       aa.login, aa.pass, aa.token, aa.login_mode, aa.claude_credentials, aa.updated_at
                FROM {}.agents_accounts aa
                WHERE aa.agent_id = %s
                  AND aa.id <> COALESCE(%s, -1)
                  AND aa.status <> 2
                  AND (
                    aa.claude_credentials IS NOT NULL
                    OR NULLIF(TRIM(COALESCE(aa.token, '')), '') IS NOT NULL
                    OR NULLIF(TRIM(COALESCE(aa.pass, '')), '') IS NOT NULL
                  )
                ORDER BY aa.is_active DESC, aa.updated_at DESC NULLS LAST, aa.id DESC
                LIMIT %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (agent_id, exclude_account_id, limit),
        )
        return [dict(r) for r in cur.fetchall()]


def set_agent_account_active(account_id: int, active: bool = True) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("SELECT agent_id FROM {}.agents_accounts WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (account_id,),
        )
        row = cur.fetchone()
        if not row:
            return False
        agent_id = row["agent_id"]
        if active:
            cur.execute(
                sql.SQL("UPDATE {}.agents_accounts SET is_active = FALSE WHERE agent_id = %s").format(
                    sql.Identifier(SCHEMA_NAME)
                ),
                (agent_id,),
            )
        cur.execute(
            sql.SQL("UPDATE {}.agents_accounts SET is_active = %s, updated_at = %s WHERE id = %s").format(
                sql.Identifier(SCHEMA_NAME)
            ),
            (active, now, account_id),
        )
        return cur.rowcount > 0


def set_agent_account_token(account_id: int, token: Optional[str]) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {}.agents_accounts SET token = %s, updated_at = %s WHERE id = %s").format(
                sql.Identifier(SCHEMA_NAME)
            ),
            (token, now, account_id),
        )
        return cur.rowcount > 0


def set_agent_account_claude_credentials(account_id: int, credentials: Optional[dict]) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    payload = json.dumps(credentials) if credentials is not None else None
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {}.agents_accounts SET claude_credentials = %s::jsonb, updated_at = %s WHERE id = %s").format(
                sql.Identifier(SCHEMA_NAME)
            ),
            (payload, now, account_id),
        )
        return cur.rowcount > 0


# --- Priorities ---

def list_priorities(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, icon, status, created_at, updated_at
                    FROM {}.priorities
                    WHERE name ILIKE %s OR shortname ILIKE %s
                    ORDER BY id ASC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, icon, status, created_at, updated_at
                    FROM {}.priorities
                    ORDER BY id ASC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_priority(
    name: str,
    shortname: str,
    icon: Optional[str] = None,
    status: int = 1,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.priorities
                    (name, shortname, icon, status, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                RETURNING id, name, shortname, icon, status, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, icon, status, now, now),
        )
        return dict(cur.fetchone())


def update_priority(
    priority_id: int,
    name: str,
    shortname: str,
    icon: Optional[str] = None,
    status: int = 1,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.priorities
                SET name = %s,
                    shortname = %s,
                    icon = %s,
                    status = %s,
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, icon, status, now, priority_id),
        )
        return cur.rowcount > 0


def delete_priority(priority_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.priorities WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (priority_id,),
        )
        return cur.rowcount > 0


# --- Workers ---

def list_workers(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT w.id, w.name, w.shortname, w.role, w.is_agent, w.agent_id,
                           a.name AS agent_name, w.status, w.avatar_url, w.created_at, w.updated_at
                    FROM {}.workers w
                    LEFT JOIN {}.agents a ON a.id = w.agent_id
                    WHERE w.name ILIKE %s OR w.shortname ILIKE %s
                       OR COALESCE(w.role, '') ILIKE %s
                    ORDER BY w.id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
                (like, like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT w.id, w.name, w.shortname, w.role, w.is_agent, w.agent_id,
                           a.name AS agent_name, w.status, w.avatar_url, w.created_at, w.updated_at
                    FROM {}.workers w
                    LEFT JOIN {}.agents a ON a.id = w.agent_id
                    ORDER BY w.id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_worker(
    name: str,
    shortname: str,
    role: Optional[str] = None,
    is_agent: bool = False,
    agent_id: Optional[int] = None,
    status: int = 0,
    avatar_url: Optional[str] = None,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.workers
                    (name, shortname, role, is_agent, agent_id, status, avatar_url, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, name, shortname, role, is_agent, agent_id, status, avatar_url, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, role, is_agent, agent_id, status, avatar_url, now, now),
        )
        return dict(cur.fetchone())


def update_worker(
    worker_id: int,
    name: str,
    shortname: str,
    role: Optional[str] = None,
    is_agent: bool = False,
    agent_id: Optional[int] = None,
    status: int = 0,
    avatar_url: Optional[str] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.workers
                SET name = %s,
                    shortname = %s,
                    role = %s,
                    is_agent = %s,
                    agent_id = %s,
                    status = %s,
                    avatar_url = %s,
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (name, shortname, role, is_agent, agent_id, status, avatar_url, now, worker_id),
        )
        return cur.rowcount > 0


def delete_worker(worker_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.workers WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (worker_id,),
        )
        return cur.rowcount > 0


# --- Task Statuses ---

def list_task_statuses(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, nom, name, shortname, status_to, color, status, created_at, updated_at
                    FROM {}.tasks_statuses
                    WHERE name ILIKE %s OR shortname ILIKE %s
                    ORDER BY nom ASC NULLS LAST, id ASC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, nom, name, shortname, status_to, color, status, created_at, updated_at
                    FROM {}.tasks_statuses
                    ORDER BY nom ASC NULLS LAST, id ASC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_task_status(
    name: str,
    shortname: str,
    status_to: Optional[str] = None,
    color: Optional[str] = None,
    status: int = 1,
    nom: Optional[int] = None,
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.tasks_statuses
                    (nom, name, shortname, status_to, color, status, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id, nom, name, shortname, status_to, color, status, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (nom, name, shortname, status_to, color, status, now, now),
        )
        return dict(cur.fetchone())


def update_task_status(
    status_id: int,
    name: str,
    shortname: str,
    status_to: Optional[str] = None,
    color: Optional[str] = None,
    status: int = 1,
    nom: Optional[int] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.tasks_statuses
                SET nom = %s, name = %s, shortname = %s, status_to = %s, color = %s, status = %s, updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (nom, name, shortname, status_to, color, status, now, status_id),
        )
        return cur.rowcount > 0


def delete_task_status(status_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.tasks_statuses WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (status_id,),
        )
        return cur.rowcount > 0


def pick_available_agent_account(provider: str) -> Optional[dict]:
    """Pick an active (status=1, is_active=1) agent account matching provider name."""
    provider_key = (provider or "").strip().lower()
    if not provider_key:
        return None
    like = f"%{provider_key.split('-', 1)[0]}%"
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id, a.name AS agent_name,
                       aa.status, aa.token
                FROM {}.agents_accounts aa
                LEFT JOIN {}.agents a ON a.id = aa.agent_id
                WHERE aa.status = 1
                  AND aa.is_active = TRUE
                  AND (LOWER(COALESCE(a.shortname, '')) LIKE %s OR LOWER(COALESCE(a.name, '')) LIKE %s)
                ORDER BY aa.updated_at NULLS FIRST, aa.id
                LIMIT 1
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
            (like, like),
        )
        row = cur.fetchone()
        if row:
            return dict(row)
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id, a.name AS agent_name,
                       aa.status, aa.token
                FROM {}.agents_accounts aa
                LEFT JOIN {}.agents a ON a.id = aa.agent_id
                WHERE aa.status = 1
                  AND aa.is_active = TRUE
                ORDER BY aa.updated_at NULLS FIRST, aa.id
                LIMIT 1
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
        )
        fallback = cur.fetchone()
        return dict(fallback) if fallback else None


def set_task_agent_account(task_id: int, account_id: Optional[int]) -> None:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("UPDATE {} SET agent_account_id = %s WHERE id = %s").format(_tasks_ref()),
            (account_id, task_id),
        )


def update_agent_account_limits(
    account_id: int,
    *,
    status: Optional[int] = None,
    percent_5h: Optional[float] = None,
    percent_7d: Optional[float] = None,
    balance_tokens: Optional[int] = None,
    reset_5h: Optional[datetime] = None,
    reset_7d: Optional[datetime] = None,
) -> None:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.agents_accounts
                SET status = COALESCE(%s, status),
                    percent_5h = COALESCE(%s, percent_5h),
                    percent_7d = COALESCE(%s, percent_7d),
                    balance_tokens = COALESCE(%s, balance_tokens),
                    reset_5h = COALESCE(%s, reset_5h),
                    reset_7d = COALESCE(%s, reset_7d),
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (status, percent_5h, percent_7d, balance_tokens, reset_5h, reset_7d, now, account_id),
        )


def list_agent_accounts_for_limits(limit: int = 1000) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id, aa.status, aa.token,
                       aa.is_active,
                       a.name AS agent_name, a.shortname AS agent_shortname
                FROM {}.agents_accounts aa
                LEFT JOIN {}.agents a ON a.id = aa.agent_id
                ORDER BY aa.id
                LIMIT %s
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
            (limit,),
        )
        return [dict(r) for r in cur.fetchall()]


def list_agent_accounts_for_limits_all(limit: int = 1000) -> list[dict]:
    """List all non-disabled accounts with credentials for comprehensive limit polling."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT aa.id, aa.name, aa.shortname, aa.agent_id, aa.status, aa.token,
                       aa.is_active, aa.login, aa.claude_credentials,
                       a.name AS agent_name, a.shortname AS agent_shortname
                FROM {}.agents_accounts aa
                LEFT JOIN {}.agents a ON a.id = aa.agent_id
                WHERE aa.status <> 2
                ORDER BY aa.is_active DESC, aa.id
                LIMIT %s
                """
            ).format(sql.Identifier(SCHEMA_NAME), sql.Identifier(SCHEMA_NAME)),
            (limit,),
        )
        return [dict(r) for r in cur.fetchall()]


def list_prompts(search: Optional[str] = None, limit: int = 200) -> list[dict]:
    with _connect() as conn, conn.cursor() as cur:
        if search:
            like = f"%{search.strip()}%"
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, message, options, status, created_at, updated_at
                    FROM {}.prompts
                    WHERE name ILIKE %s OR shortname ILIKE %s OR message ILIKE %s
                    ORDER BY id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (like, like, like, limit),
            )
        else:
            cur.execute(
                sql.SQL(
                    """
                    SELECT id, name, shortname, message, options, status, created_at, updated_at
                    FROM {}.prompts
                    ORDER BY id DESC
                    LIMIT %s
                    """
                ).format(sql.Identifier(SCHEMA_NAME)),
                (limit,),
            )
        return [dict(r) for r in cur.fetchall()]


def create_prompt(
    name: str, shortname: str, message: str, options: Optional[dict] = None, status: int = 1
) -> dict:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                INSERT INTO {}.prompts
                    (name, shortname, message, options, status, created_at, updated_at)
                VALUES (%s, %s, %s, %s::jsonb, %s, %s, %s)
                RETURNING id, name, shortname, message, options, status, created_at, updated_at
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (
                name,
                shortname,
                message,
                json.dumps(options) if options is not None else None,
                status,
                now,
                now,
            ),
        )
        return dict(cur.fetchone())


def update_prompt(
    prompt_id: int,
    name: str,
    shortname: str,
    message: str,
    options: Optional[dict] = None,
    status: Optional[int] = None,
) -> bool:
    now = datetime.utcnow().replace(microsecond=0)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                UPDATE {}.prompts
                SET name = %s,
                    shortname = %s,
                    message = %s,
                    options = %s::jsonb,
                    status = COALESCE(%s, status),
                    updated_at = %s
                WHERE id = %s
                """
            ).format(sql.Identifier(SCHEMA_NAME)),
            (
                name,
                shortname,
                message,
                json.dumps(options) if options is not None else None,
                status,
                now,
                prompt_id,
            ),
        )
        return cur.rowcount > 0


def delete_prompt(prompt_id: int) -> bool:
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {}.prompts WHERE id = %s").format(sql.Identifier(SCHEMA_NAME)),
            (prompt_id,),
        )
        return cur.rowcount > 0


# Auto-init on import
init_db()
